if(!process.env.HUNTMAPS_URL||!process.env.HUNTMAPS_SCREENSHOTS)throw Error('Run through ./gui/check with an isolated server and screenshot directory');
const base=process.env.HUNTMAPS_URL;
import {chromium} from 'playwright';
import fs from 'node:fs';
const out=process.env.HUNTMAPS_SCREENSHOTS;fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.HUNTMAPS_BROWSER||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1500,height:1050}});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});page.on('request',r=>{if(r.url().startsWith('http')&&!r.url().startsWith(base))external.push(r.url())});
await page.addInitScript(()=>localStorage.setItem('huntmaps-online-imagery','off'));await page.goto(base);
const originalAnnotations=await (await page.request.get(base+'/api/runs/soap-creek-decision-review-v2/annotations')).json();
const jobsBefore=await (await page.request.get(base+'/api/jobs')).json();await page.getByLabel('Select A0075',{exact:true}).click();await page.locator('.selected-setup').getByText('0.485 mi²',{exact:true}).waitFor();await page.waitForTimeout(5000);await page.screenshot({path:out+'/01-viewer.png',fullPage:true});
if(await page.locator('.setup-group summary').count()) await page.locator('.setup-group summary').first().click();
for(const [id,area] of [['V010','0.508 mi²'],['V008','0.500 mi²'],['A0075','0.485 mi²']]){await page.getByLabel('Select '+id,{exact:true}).click();await page.locator('.selected-setup').getByText(area,{exact:true}).waitFor();await page.getByLabel('Compare '+id,{exact:true}).check();}
await page.getByText('0.247 mi² under 10% trees',{exact:false}).waitFor();await page.getByText('Compare setups',{exact:true}).waitFor();await page.getByLabel('Show V010 view',{exact:true}).uncheck();await page.getByLabel('Show V010 view',{exact:true}).check();await page.waitForTimeout(3000);await page.screenshot({path:out+'/02-compare.png',fullPage:true});
await page.getByLabel('Saved neighborhood').selectOption('West');await page.getByLabel('Compare A0081',{exact:true}).click();await page.getByRole('alert').getByText('Compare up to three setups.',{exact:false}).waitFor();await page.getByRole('button',{name:'Dismiss error'}).click();
if(!(await page.locator('.layers').getAttribute('open') !== null)) await page.locator('.layers > summary').click();await page.getByText('Tree-cover classes for active setup',{exact:true}).click();await page.getByText('Saved inspection sectors',{exact:true}).click();await page.waitForTimeout(2000);await page.screenshot({path:out+'/05-classes-sectors.png',fullPage:true});
await page.getByText('Tree-cover classes for active setup',{exact:true}).click();await page.getByText('Saved inspection sectors',{exact:true}).click();
await page.getByLabel('Export A0075',{exact:true}).check();await page.getByLabel('Export V010',{exact:true}).check();await page.getByLabel('Export V008',{exact:true}).check();
const response=await page.request.get(base+'/api/runs/soap-creek-decision-review-v2/export/gpx?ids=A0075,V010,V008');fs.writeFileSync(out+'/observers.gpx',await response.body());
// Offline external-network simulation retains local HTTP and blocks every other origin.
await page.route('**/*',route=>route.request().url().startsWith(base)||route.request().url().startsWith('blob:')?route.continue():route.abort());await page.reload();await page.getByLabel('Select A0075',{exact:true}).click();await page.getByRole('button',{name:'Setup details',exact:true}).click();await page.getByLabel('Candidate notes').waitFor();if(await page.getByLabel('Candidate notes').inputValue()!==(originalAnnotations.A0075?.notes||''))throw Error('Notes did not persist');await page.locator('.selected-setup').getByText('0.485 mi²',{exact:true}).waitFor();await page.waitForTimeout(3000);await page.screenshot({path:out+'/03-offline.png',fullPage:true});
await page.getByRole('button',{name:'+ New area'}).click();await page.getByRole('button',{name:'Import file',exact:true}).click();await page.getByLabel('Import observer polygon').setInputFiles(process.env.HUNTMAPS_IMPORT_FILE||'../../inputs/test.kml');await page.getByLabel('Polygon selection').waitFor();await page.waitForTimeout(1500);await page.screenshot({path:out+'/04-import.png',fullPage:true});
await page.getByRole('button',{name:'Back to review',exact:true}).click();await page.getByLabel('Run selector').selectOption('soap-creek-v1');await page.getByLabel('Select A0075',{exact:true}).click();await page.locator('.selected-setup').getByText('0.485 mi²',{exact:true}).waitFor();await page.waitForTimeout(2000);await page.screenshot({path:out+'/06-baseline.png',fullPage:true});
if(!(await page.locator('.layers').getAttribute('open') !== null)) await page.locator('.layers > summary').click();await page.getByText('Cached aerial imagery',{exact:true}).click();await page.waitForTimeout(1500);await page.screenshot({path:out+'/09-hillshade.png',fullPage:true});
const jobsAfter=await (await page.request.get(base+'/api/jobs')).json();if(jobsBefore.length!==jobsAfter.length)throw Error('Viewer triggered a job');
fs.writeFileSync(out+'/browser-results.json',JSON.stringify({errors,external,title:await page.title(),screenshots:out},null,2));await browser.close();if(errors.length||external.length)throw Error(JSON.stringify({errors,external}));console.log('Browser viewer, compare, notes, offline, export and import verified:',out);
